version: "3.9"
services:
  postgres:
    container_name: iot-online-shop-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env

  pgadmin:
    links:
      - postgres:postgres
    container_name: iot-online-shop-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - docker.env

  gooddata:
    container_name: gooddata
    image: gooddata/gooddata-cn-ce:latest
    ports:
      - "3000:3000"
    volumes:
      - /data
    stdin_open: true
    tty: true
    environment:
      - BUNDLE_TYPE=article_build_tool_for_data_analysis
      - LICENSE_AND_PRIVACY_POLICY_ACCEPTED=YES
